### ISSUE TITLE
file can't find

### ISSUE THREAD

**Issue by ZQ32** [Kinovarobotics/matlab_kortex#3]
Hello, test_api_cotrol.m was not found in the folder you provided

**Comment by gstlaurentkinova** [comment]
Hi @ZQ32,

The file `test_api_control.m` has been correctly added as part of the [`2.2` release of our MATLAB adaptor](https://artifactory.kinovaapps.com/artifactory/webapp/#/artifacts/browse/tree/General/generic-public/kortex/matlab/simplified_API/2.2.0). I suggest you try downloading the new package.

Hope this answers your question.

Best,

Gabriel
